# Generated by Django 4.2.7 on 2023-11-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
