# Generated by Django 4.2.7 on 2023-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.CharField(default='Black', max_length=100),
        ),
    ]
