# Generated by Django 4.2.7 on 2023-11-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='color',
        ),
        migrations.AlterModelTable(
            name='article',
            table='articles',
        ),
    ]
